#端口号
server:
  port: 8081

#rabbitmq配置连接
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    #    这是连接集群方式
    addresses: 49.235.125.139:5672
#    这是连接非集群方式  单机模式
#    host: 49.235.125.139
#    port: 5672